### ISSUE TITLE
To do next... (a short task list)

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/brand-logo#15]
- [x] Create some sort of better preview replacing the table in the README.md. We need a grey background so we can view the white paths and outlines. Clem wants to achieve this preview with a Python script. Another possibility would be to create a `preview.svg` like this #16.
 - [x] Once we got this preview done, we can convert all the grey paths and strokes to white: `sed -i 's/#505050/#ffffff/g' *.svg` (Just one command for all the SVG files !)
 - [ ] Consider adding information about license and copyright ?

**Comment by SebastJava** [comment]
@clefebvre Are you still doing this Python script for preview ? That's step number 2 here on this task list...

 Else i could do something like this:

![brand-logo-preview](https://user-images.githubusercontent.com/31940713/133909024-3b9aa655-82d5-4cc8-b003-48b031f96b26.png)

I could do this for all the different logo versions. Complete description: #7

**Comment by SebastJava** [comment]
Checked the 3 first tasks here with just one PR: #16

**Comment by Secret-chest** [comment]
> * Change the logo and brand colour ? You want to avoid grass green. Then it can either be the current greyish yellow-green (bad !) or some turquoise green (good !). Example: #00B894. (That's the "MintLeaf" from https://flatuicolors.com/palette/us)

Would you like ```#009688```?

**Comment by SebastJava** [comment]
@Secret-chest This is just a quick answer, just for fun... This repository is "frozen", so I don't want to waste my time here. I guess I'll be back when this is back to life. Besides, I don't like this official logo so much. Okay, at least it isn't bad. Not ugly. Not messy. Much better than the old one still being used on the LM-forums and elsewhere. But this official logo doesn't have much significance and power. I went totally off, on my own tracks. I have my own, parallel and unofficial repository: https://github.com/SebastJava/linuxmint-logo

![trident-name](https://user-images.githubusercontent.com/31940713/147857338-510e6ec3-d6a2-458f-9198-1e8ece5a3f77.png)

**That was just a small parenthesis. Now back to your colour proposal...**

I don't like their official yellowish-greyish-green. Pretty much any other colour would be better.
Your latest: `#009688` = 174,100,29 (HSL)
**Hue 174** ? Good idea, but I'd say 175: I like round numbers.
**Saturation 100%** ? Yes !
**Lightness 29** ? That's too dark, IMHO. I'd say 33... Darkening it just enough so it gets a colour contrast around 3...

So, I would say `#00A699`
https://colorable.jxnblk.com/ffffff/00a699

**Comment by Secret-chest** [comment]
> @Secret-chest This is just a quick answer, just for fun... This repository is "frozen", so I don't want to waste my time here. I guess I'll be back when this is back to life. Besides, I don't like this official logo so much. Okay, at least it isn't bad. Not ugly. Not messy. Much better than the old one still being used on the LM-forums and elsewhere. But this official logo doesn't have much significance and power. I went totally off, on my own tracks. I have my own, parallel and unofficial repository: https://github.com/SebastJava/linuxmint-logo
> 
> ![trident-name](https://user-images.githubusercontent.com/31940713/147857338-510e6ec3-d6a2-458f-9198-1e8ece5a3f77.png)
> 
> **That was just a small parenthesis. Now back to your colour proposal...**
> 
> I don't like their official yellowish-greyish-green. Pretty much any other colour would be better.
> Your latest: `#009688` = 174,100,29 (HSL)
> **Hue 174** ? Good idea, but I'd say 175: I like round numbers.
> **Saturation 100%** ? Yes !
> **Lightness 29** ? That's too dark, IMHO. I'd say 33... Darkening it just enough so it gets a colour contrast around 3...
> 
> So, I would say `#00A699`
> https://colorable.jxnblk.com/ffffff/00a699

Too bright. View it in a larger area, and you'll love it...

**Comment by SebastJava** [comment]
`#00A699`

![badge-00A699](https://user-images.githubusercontent.com/31940713/147859782-4677cbce-02ba-4c28-8096-4bf10b525206.png)

**Comment by Secret-chest** [comment]
> ```#00A699```
```#26a69a``` for the lighter part and ```#009688``` for the darker part (remember my two-tone idea?)
